function windowChrome(title){return '<div class="titlebar"><div class="dots"><button class="dot r" data-act="close" title="关闭"></button><button class="dot y" data-act="min" title="最小化"></button><button class="dot g" data-act="max" title="最大化"></button></div><div class="name">'+title+'</div></div>'}
function buildLayer(root,variant){if(!root)return;root.innerHTML='<div class="icons"><div class="desk-icon"><div class="pic">💻</div>计算机</div><div class="desk-icon"><div class="pic">🏠</div>主目录</div><div class="desk-icon"><div class="pic">🗑</div>回收站</div></div><div class="win win-fm" data-win="fm">'+windowChrome('文件管理器 — 文档')+'<div class="win-body fm-layout"><div class="fm-side"><div class="on">主目录</div><div>桌面</div><div>文档</div><div>下载</div><div>图片</div></div><div class="fm-grid"><div class="fm-item"><div class="f"></div>项目</div><div class="fm-item"><div class="f doc"></div>设计稿</div><div class="fm-item"><div class="f pic"></div>截图</div><div class="fm-item"><div class="f"></div>归档</div></div></div></div><div class="win dark win-term" data-win="term">'+windowChrome('终端 — zsh')+'<div class="win-body term-body"><div><span class="dim">zccrs@deepin</span> <span class="cmd">~</span> $ ls</div><div>'+(variant==='new'?'切换中…':'waiting…')+'<span class="blink"></span></div></div></div><div class="win dark win-music" data-win="music">'+windowChrome('音乐')+'<div class="win-body music-body"><div class="cover"></div><div class="music-meta"><h3>'+(variant==='new'?'Alpine Air':'Lake Shore')+'</h3><p>Ambient</p><div class="bar"><i></i></div></div></div></div>'}
const THEMES={lake:{name:"湖畔",tone:"dark",accent:"#0081ff",wallpapers:["https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1920&q=80","https://images.unsplash.com/photo-1439066615861-d1af74d74039?auto=format&fit=crop&w=1920&q=80","https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?auto=format&fit=crop&w=1920&q=80"],desk:["💻","🏠","🗑"],dock:["🗂","🌐","🎵","🖥","🗒","⚙️"]},alpine:{name:"高山",tone:"light",accent:"#2f6fed",wallpapers:["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1920&q=80","https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1920&q=80","https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?auto=format&fit=crop&w=1920&q=80"],desk:["🖥️","🏡","♻️"],dock:["📁","🌍","🎧","💻","📝","🛠"]},dusk:{name:"暮色",tone:"dark",accent:"#ff7a45",wallpapers:["https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1920&q=80","https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?auto=format&fit=crop&w=1920&q=80","https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=1920&q=80"],desk:["🌙","📂","🗑️"],dock:["🗂","🔥","🎶","📺","📌","⚙️"]},paper:{name:"纸白",tone:"light",accent:"#111111",wallpapers:["https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=1920&q=80","https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1920&q=80","https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1920&q=80"],desk:["📄","🏠","📎"],dock:["📒","🧭","🎹","🖥","✏️","🔧"]}};
const slider=document.getElementById("slider");const desktop=document.getElementById("desktop");const frameSnap=document.getElementById("frameSnap");const swDark=document.getElementById("swDark");const comboTheme=document.getElementById("comboTheme");const comboBtn=document.getElementById("comboBtn");const comboList=document.getElementById("comboList");const inpDur=document.getElementById("inpDur");const swFadeL=document.getElementById("swFadeL");const swFadeR=document.getElementById("swFadeR");const btnWp=document.getElementById("btnWp");const btnReset=document.getElementById("btnReset");const hud=document.getElementById("hud");const guide=document.getElementById("guide");
buildLayer(document.getElementById("wins-old"),"old");buildLayer(document.getElementById("wins-new"),"new");
let durMs=5000,playing=false,showingNew=false,playMode="wallpaper",raf=0,currentThemeId="lake",wpIndex=0,forceDark=true,fadeLeft=true,fadeRight=true;
Object.keys(THEMES).forEach(id=>{const t=THEMES[id];const b=document.createElement("button");b.type="button";b.dataset.id=id;b.textContent=t.name+" · "+(t.tone==="dark"?"暗色":"亮色");comboList.appendChild(b)});
function setDurCss(){const v=durMs+"ms";slider.style.setProperty("--dur",v);frameSnap.style.setProperty("--dur",v);desktop.style.setProperty("--dur",v)}setDurCss();
function setShowingNew(v){showingNew=v;slider.classList.toggle("show-new",v)}
function syncFadeFlags(){slider.classList.toggle("fade-left",fadeLeft);slider.classList.toggle("fade-right",fadeRight)}
function wireSwitch(btn,getter,setter){btn.addEventListener("click",()=>{const next=!getter();setter(next);btn.classList.toggle("on",next);btn.setAttribute("aria-checked",next?"true":"false");syncFadeFlags()})}
function wpUrl(themeId,index){const list=THEMES[themeId].wallpapers;return list[((index%list.length)+list.length)%list.length]}
function setWallpaperEl(el,url){if(!el||!url)return;el.style.backgroundImage='url("'+url+'")';el.style.backgroundSize="cover";el.style.backgroundPosition="center"}
function applyIcons(theme){desktop.querySelectorAll(".icons").forEach(row=>{row.querySelectorAll(".desk-icon .pic").forEach((pic,i)=>{if(theme.desk[i])pic.textContent=theme.desk[i]})});const dock=desktop.querySelector(".dock");if(!dock)return;const slots=dock.querySelectorAll(".dock-ico");theme.dock.forEach((ico,i)=>{if(slots[i])slots[i].textContent=ico})}
function themeOptionLabel(id){const t=THEMES[id];return t.name+" · "+(t.tone==="dark"?"暗色":"亮色")}
function updateWpBtn(){btnWp.disabled=playing||THEMES[currentThemeId].wallpapers.length<2}
function applyPack(themeId,index,dark){const t=THEMES[themeId];currentThemeId=themeId;wpIndex=index;forceDark=dark;desktop.setAttribute("data-theme",dark?"dark":"light");desktop.style.setProperty("--accent",t.accent);document.documentElement.style.setProperty("--accent",t.accent);setWallpaperEl(desktop.querySelector(".screen-old .wallpaper"),wpUrl(themeId,index));setWallpaperEl(desktop.querySelector(".screen-new .wallpaper"),wpUrl(themeId,index+1));applyIcons(t);swDark.classList.toggle("on",dark);swDark.setAttribute("aria-checked",dark?"true":"false");comboBtn.textContent=themeOptionLabel(themeId);comboList.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.id===themeId));updateWpBtn()}
function settleAsCurrent(){slider.classList.remove("animating");setShowingNew(false);setWallpaperEl(desktop.querySelector(".screen-old .wallpaper"),wpUrl(currentThemeId,wpIndex));setWallpaperEl(desktop.querySelector(".screen-new .wallpaper"),wpUrl(currentThemeId,wpIndex+1));void slider.offsetWidth}
function tick(){updateGuide();if(playing)raf=requestAnimationFrame(tick)}
function setBusy(v){swDark.disabled=v;comboBtn.disabled=v;inpDur.disabled=v;if(v)comboTheme.classList.remove("open");updateWpBtn();if(v)btnWp.disabled=true}
function playWallpaper(){if(playing)return;playMode="wallpaper";const next=wpIndex+1;setWallpaperEl(desktop.querySelector(".screen-new .wallpaper"),wpUrl(currentThemeId,next));slider.classList.remove("animating","show-new");syncFadeFlags();void slider.offsetWidth;playing=true;setBusy(true);slider.classList.add("animating");setShowingNew(true);raf=requestAnimationFrame(tick);window.setTimeout(()=>{playing=false;cancelAnimationFrame(raf);wpIndex=next%THEMES[currentThemeId].wallpapers.length;settleAsCurrent();setBusy(false);updateGuide()},durMs+40)}
function captureFrame(){frameSnap.innerHTML="";frameSnap.classList.remove("wiping","show");const clone=desktop.cloneNode(true);clone.removeAttribute("id");clone.querySelectorAll("[id]").forEach(el=>el.removeAttribute("id"));clone.style.pointerEvents="none";frameSnap.appendChild(clone);frameSnap.classList.add("show");void frameSnap.offsetWidth}
function clearFrame(){frameSnap.classList.remove("show","wiping");frameSnap.innerHTML=""}
function setLayerFade(root,value,withTransition){root.querySelectorAll(".screen-old .layer-windows").forEach(el=>{el.style.transition=withTransition?("opacity "+durMs+"ms cubic-bezier(.45,0,.2,1)"):"none";el.style.opacity=String(value)})}
function clearLayerFade(root){root.querySelectorAll(".screen-old .layer-windows").forEach(el=>{el.style.transition="";el.style.opacity=""})}
function playFrameWipe(beforeWipe){if(playing)return false;playMode="frame";captureFrame();setLayerFade(frameSnap,1,false);beforeWipe();setLayerFade(desktop,fadeLeft?0:1,false);void desktop.offsetWidth;playing=true;setBusy(true);requestAnimationFrame(()=>requestAnimationFrame(()=>{frameSnap.classList.add("wiping");if(fadeRight)setLayerFade(frameSnap,0,true);if(fadeLeft)setLayerFade(desktop,1,true);else setLayerFade(desktop,1,false);raf=requestAnimationFrame(tick)}));window.setTimeout(()=>{playing=false;cancelAnimationFrame(raf);clearFrame();clearLayerFade(desktop);setBusy(false);updateGuide()},durMs+40);return true}
function updateGuide(){const view=desktop.getBoundingClientRect();guide.style.opacity=playing?"0.85":"0";if(!playing){const t=THEMES[currentThemeId];hud.textContent=t.name+" · "+(forceDark?"Dark":"Light")+" · 壁纸 "+(wpIndex+1)+"/"+t.wallpapers.length}}
function reset(){playing=false;cancelAnimationFrame(raf);slider.classList.remove("animating");setShowingNew(false);clearFrame();applyPack("lake",0,true);setBusy(false);document.querySelectorAll(".win").forEach(w=>w.classList.remove("maximized","fullscreen","minimized","focused"));updateGuide()}
swDark.addEventListener("click",()=>{if(playing)return;playFrameWipe(()=>applyPack(currentThemeId,wpIndex,!forceDark))});
comboBtn.addEventListener("click",()=>{if(!comboBtn.disabled)comboTheme.classList.toggle("open")});
comboList.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;comboTheme.classList.remove("open");const id=b.dataset.id;if(playing||id===currentThemeId)return;playFrameWipe(()=>applyPack(id,0,THEMES[id].tone==="dark"))});
document.addEventListener("click",e=>{if(!comboTheme.contains(e.target))comboTheme.classList.remove("open")});
wireSwitch(swFadeL,()=>fadeLeft,v=>fadeLeft=v);wireSwitch(swFadeR,()=>fadeRight,v=>fadeRight=v);syncFadeFlags();
inpDur.addEventListener("change",()=>{const n=Math.min(20,Math.max(.5,parseFloat(inpDur.value)||5));inpDur.value=n;durMs=n*1000;setDurCss()});
btnWp.addEventListener("click",playWallpaper);btnReset.addEventListener("click",reset);window.addEventListener("resize",updateGuide);
function applyWin(id,fn){document.querySelectorAll('.win[data-win="'+id+'"]').forEach(fn)}
function focusWin(id){document.querySelectorAll(".win").forEach(w=>w.classList.remove("focused"));applyWin(id,w=>w.classList.add("focused"))}
function toggleMax(id){const any=document.querySelector('.win[data-win="'+id+'"]');const isFs=any.classList.contains("fullscreen");const isMax=any.classList.contains("maximized");applyWin(id,w=>{w.classList.remove("minimized");if(isFs)w.classList.remove("fullscreen","maximized");else if(isMax){w.classList.remove("maximized");w.classList.add("fullscreen")}else{w.classList.add("maximized");w.classList.remove("fullscreen")}});focusWin(id)}
function toggleFullscreen(id){const any=document.querySelector('.win[data-win="'+id+'"]');const next=!any.classList.contains("fullscreen");applyWin(id,w=>{w.classList.toggle("fullscreen",next);if(next)w.classList.remove("maximized","minimized")});focusWin(id)}
slider.addEventListener("click",e=>{const win=e.target.closest(".win");if(!win)return;const id=win.getAttribute("data-win");const act=e.target.getAttribute("data-act");if(act==="max"){toggleMax(id);return}if(act==="min"||act==="close"){applyWin(id,w=>{w.classList.add("minimized");w.classList.remove("maximized","focused")});return}focusWin(id)});
slider.addEventListener("dblclick",e=>{const bar=e.target.closest(".titlebar");if(!bar||e.target.closest("[data-act]"))return;const win=bar.closest(".win");if(win)toggleFullscreen(win.getAttribute("data-win"))});
applyPack(currentThemeId,wpIndex,forceDark);updateGuide();
